Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,8 +20,15 @@ jobs:
         run: pip install poetry
       - name: Install dependencies
         run: poetry install && pip install pylint
-      - name: Lint
-        run: pylint src/
+      - name: Run Pylint
+        run: |
+          pylint src/
+          pylint_exit_code=$?
+  
+          if [ $pylint_exit_code -ne 0 ]; then
+            echo "Pylint check failed."
+            exit 1
+          fi
       - name: Run tests
         run: poetry run coverage run --branch -m pytest
       - name: Coverage report
